apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  creationTimestamp: null
  labels:
    created-by: kubeless
    function: checkface
  name: checkface
  namespace: default
spec:
  checksum: sha256:6c9432e25da54e33038e0fab6d054010803ce7f44b7c4db6b71804a9ea257bc6
  deployment:
    metadata:
      creationTimestamp: null
    spec:
      selector: null
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - imagePullPolicy: Always
            name: ""
            resources: {}
            volumeMounts:
            - mountPath: /kubeless/model
              name: my-model

            resources: {}
          volumes:
          - name: my-model
            hostPath: 
              path: /my-model
    status: {}
  deps: |
    absl-py==0.15.0
    asgiref==3.4.1
    astunparse==1.6.3
    cached-property==1.5.2
    cachetools==4.2.4
    certifi==2021.10.8
    charset-normalizer==2.0.7
    clang==5.0
    dataclasses==0.6
    Django==3.2.8
    flatbuffers==1.12
    gast==0.4.0
    google-auth==2.3.2
    google-auth-oauthlib==0.4.6
    google-pasta==0.2.0
    grpcio==1.41.1
    h5py==3.1.0
    idna==3.3
    importlib-metadata==4.8.1
    keras==2.6.0
    Keras-Preprocessing==1.1.2
    Markdown==3.3.4
    numpy==1.19.5
    oauthlib==3.1.1
    opt-einsum==3.3.0
    Pillow==8.4.0
    protobuf==3.19.1
    pyasn1==0.4.8
    pyasn1-modules==0.2.8
    pytz==2021.3
    requests==2.26.0
    requests-oauthlib==1.3.0
    rsa==4.7.2
    six==1.15.0
    sqlparse==0.4.2
    tensorboard==2.7.0
    tensorboard-data-server==0.6.1
    tensorboard-plugin-wit==1.8.0
    tensorflow==2.6.0
    tensorflow-estimator==2.6.0
    termcolor==1.1.0
    typing-extensions==3.7.4.3
    urllib3==1.26.7
    Werkzeug==2.0.2
    wrapt==1.12.1
    zipp==3.6.0
  function: "\nfrom keras.models import load_model\nfrom PIL import Image, ImageOps\nimport
    numpy as np\nimport urllib.request\nfrom io import BytesIO\n\ndef handler(event,
    context):\n    print(\"event occurs\")\n    try:\n        url = event['data']['imageURL']\n
    \       # url = \"https://hanbucket-test.s3.ap-northeast-2.amazonaws.com/img.png\"\n
    \       print(url)\n        req = urllib.request.Request(url, headers = {\"User-Agent\"
    : \"Mozilla/5.0\"})\n        print(1)\n        res = urllib.request.urlopen(req).read()\n
    \       print(2)\n        image = Image.open(BytesIO(res))\n\n         # keras\n
    \       print(3)\n        model = load_model('/kubeless/model/keras_model.h5')\n
    \       print(4)\n        data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)\n
    \       print(5)\n        size = (224, 224)\n        print(6)\n        image =
    ImageOps.fit(image, size, Image.ANTIALIAS)\n        print(7)\n        image_array
    = np.asarray(image)\n        print(8)\n        normalized_image_array = (image_array.astype(np.float32)
    / 127.0) - 1\n        print(9)\n        data[0] = normalized_image_array\n        print(10)\n
    \       prediction = model.predict(data)\n        #result\n        print(\"사람:\",
    float(prediction[0][0]))\n        print(\"손바닥:\", float(prediction[0][1]))\n        return
    'ok'\n        \n    except Exception as e:\n        print(e)\n        return 'fail'\n\n
    \  \n# handler(1, 1)\n\n"
  function-content-type: text
  handler: checkface.handler
  horizontalPodAutoscaler:
    metadata:
      creationTimestamp: null
    spec:
      maxReplicas: 0
      scaleTargetRef:
        kind: ""
        name: ""
    status:
      conditions: null
      currentMetrics: null
      currentReplicas: 0
      desiredReplicas: 0
  runtime: python3.7
  service:
    ports:
    - name: http-function-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      created-by: kubeless
      function: checkface
    type: ClusterIP
  timeout: "180"
