apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  creationTimestamp: null
  labels:
    created-by: kubeless
    function: producer
  name: producer
  namespace: default
spec:
  checksum: sha256:90e884ca7f02803296789ea8a8c7cd70d1372ac42c4f0e8584386cd4dd77ddd9
  deployment:
    metadata:
      creationTimestamp: null
    spec:
      selector: null
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - imagePullPolicy: Always
            name: ""
            resources: {}
    status: {}
  deps: |
    {
      "name": "producer",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "keywords": [],
      "author": "",
      "license": "ISC",
      "dependencies": {
        "axios": "^0.24.0"
      }
    }
  function: "module.exports = {\n    producer: function async(event, context) {\n
    \       const axios = require(\"axios\");\n        console.log(event);\n        try
    {\n            \n            const data = event[\"data\"];\n            axios.post(\"http://checkface.default.svc:8080\",
    data).then((res) => {\n                console.log(res);\n                return
    \"ok\";\n            });\n        } catch (error) {\n            console.log(error)\n
    \           return \"fail\";\n        }\n\n        return \"fail\";\n    },\n};\n"
  function-content-type: text
  handler: test.producer
  horizontalPodAutoscaler:
    metadata:
      creationTimestamp: null
    spec:
      maxReplicas: 0
      scaleTargetRef:
        kind: ""
        name: ""
    status:
      conditions: null
      currentMetrics: null
      currentReplicas: 0
      desiredReplicas: 0
  runtime: nodejs6
  service:
    ports:
    - name: http-function-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      created-by: kubeless
      function: producer
    type: ClusterIP
  timeout: "180"
